import os
import os
import os
import os
from pathlib import Path
from pathlib import Path
from pathlib import Path
from pymongo import MongoClient
import dj_database_url 
import mongoengine
# from mongoengine import connect
# from dotenv import load_dotenv
# load_dotenv()   
# from dotenv import load_dotenv
# load_dotenv()
from dotenv import load_dotenv
load_dotenv()

os.environ.setdefault('DJANGO_SETTINGS_MODULE', '...')
"""
Django settings for Climate_Agency.climate_data project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2.5/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2.5/ref/settings/
"""

# Build paths inside the project like this: BASE_DIR / 'subdir'.
SECRET_KEY = os.getenv("django-insecure-climate_agency_2025_-q*biq3bty0o3d3@^tww*jgy_nnb*4zd8m51477%&cq1ms_cgmb")

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')
DEBUG = os.getenv("DEBUG") == "True"
ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "climate-eshal-fatima-web.onrender.com").split(",")

# MongoDB connection
MONGO_URI = os.getenv("MONGO_URI", "mongodb://localhost:27017/climate_agency_db")
mongoengine.connect(host=MONGO_URI)

print(f"✅ MongoDB connected successfully: {os.getenv('DATABASE_NAME', 'climate_agency_db')}")





# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-846kbei@h6@=2n4fmiqf%o^-*4ha!-fexbkdi=60_@(h!%6m70'

# SECURITY WARNING: don't run with debug turned on in production!

# SECRET_KEY = os.getenv('django-insecure-q*biq3bty0o3d3@^tww*jgy_nnb*4zd8m51477%&cq1ms_cgmb', 'django-insecure-q*biq3bty0o3d3@^tww*jgy_nnb*4zd8m51477%&cq1ms_cgmb')

# DEBUG = os.getenv('DEBUG', 'True') == 'True'

# ALLOWED_HOSTS = ['127.0.0.1,localhost']


INSTALLED_APPS = [
    'rest_framework',
    'rest_framework_simplejwt',
    'accounts',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Climate_Agency',
    'climate_data',
    'dashboard',   
    ]
# AUTH_USER_MODEL = 'accounts.CustomUser'
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    )
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Climate_Agency.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Climate_Agency.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# MONGO_DB_NAME = os.getenv('climate_agency_db')
# MONGO_URI = os.getenv('mongodb://localhost:27017/')

# MongoDB settings
DATABASE_NAME = os.getenv('DATABASE_NAME', 'climate_agency_db')
DATABASE_USER = os.getenv('DATABASE_USER', 'Syeda Nabela Shah')
MONGO_URI = os.getenv('MONGO_URI', 'mongodb://localhost:27017/climate_agency_db')

DATABASES = {
    'default': {
        'ENGINE':'djongo',
        'NAME':'climate_agency_db',  # your database name
        'ENFORCE_SCHEMA': False,
        'CLIENT':{
            # 'host':'mongodb://localhost:27017',
             'host': os.environ.get('MONGODB_URI', 'mongodb://localhost:27017/climate_agency_db'),
         }
    }
}
print("✅ MongoDB connected successfully:", DATABASES['default']['NAME'])
# DATABASES = {
#     'default': {
#         'ENGINE': 'djongo',
#         'NAME': os.environ.get('DB_NAME'),
#         'ENFORCE_SCHEMA': False,
#         'CLIENT': {
#             'host': os.environ.get('DB_HOST', '127.0.0.1'),
#             'port': int(os.environ.get('DB_PORT', 27017)),
#             'username': os.environ.get('DB_USER', 'Syeda Nabela Shah'),
#             'password': os.environ.get('DB_PASSWORD', 'eshal@123'),
#             'authSource': os.environ.get('DB_NAME','climate_agency_db'),
#         }  
#     }
# }

# apps = settings.INSTALLED_APPS
# duplicates = [app for app in apps if apps.count(app) > 1]
# print(set(duplicates))





# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]



# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True




# Static.files(CSS,JavaScript,Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATIC_URL = '/static/'

# STATICFILES_DIRS = [BASE_DIR / 'Climate_Agency' / "static"]

# TEMPLATES[0]['DIRS'] = [BASE_DIR / 'Climate_Agency'/ 'templates']

# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# # Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
